services:

  # overriders provider
  # register overriders here (and define them below).
  mcm.console.overrider_provider:
    class: MCM\Console\Overriders\Provider
    public: true
    arguments:
      $overriders:
        - '@mcm.console.overriders.demo'
        - '@mcm.console.overriders.moduletemplate'
        - '@mcm.console.overriders.legacy_core'
        - '@mcm.console.overriders.module'

  # --- overriders ---

  mcm.console.overriders.demo:
    class: MCM\Console\Overriders\DemoOverrider

  mcm.console.overriders.moduletemplate:
    class: MCM\Console\Overriders\ModuleTemplateOverrider

  mcm.console.overriders.legacy_core:
    class: MCM\Console\Overriders\LegacyCoreOverrider

  mcm.console.overriders.module:
    class: MCM\Console\Overriders\ModuleOverrider
